"use client"

import * as React from "react"
import { HeroHeader } from "@/components/header"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

type Prompt = {
  id: string
  title: string
  rules: string[]
  facts: string
  expected?: string
}

const PROMPTS: Prompt[] = [
  {
    id: "fre-403-high-high",
    title: "High probative, high prejudice (FRE 403)",
    rules: ["FRE 403"],
    facts:
      "Defendant is charged with armed robbery. The prosecution seeks to introduce photos from the defendant’s phone showing him posing with firearms similar to the one used in the robbery, taken two weeks before the incident. The defendant argues the photos are irrelevant and highly prejudicial.",
    expected:
      "Cases balancing probative value vs unfair prejudice; limits on character/propensity evidence; sometimes allowed with limiting instructions.",
  },
  {
    id: "fre-403-low-high",
    title: "Low probative, high prejudice (FRE 403)",
    rules: ["FRE 403"],
    facts:
      "In a murder trial, the prosecution offers evidence that the defendant had a violent argument with a coworker five years earlier, unrelated to the victim or the charged crime.",
  },
  {
    id: "hearsay-exception",
    title: "Hearsay with an asserted exception (Hearsay)",
    rules: ["Hearsay"],
    facts:
      "After a car accident, an injured pedestrian told a paramedic, “That blue sedan ran the red light.” The pedestrian does not testify at trial. The prosecution seeks to admit the statement.",
    expected:
      "Excited utterance / present sense impression analysis; reliability rationale; admissibility disputes.",
  },
  {
    id: "business-records",
    title: "Business records / reliability (FRE 403, 404(b))",
    rules: ["FRE 403", "FRE 404(b)"],
    facts:
      "In a civil fraud case, the plaintiff offers internal accounting spreadsheets generated by the defendant’s company to show falsified revenue. The spreadsheets were automatically generated but later edited by employees.",
    expected: "Business records exception; foundation requirements; trustworthiness challenges.",
  },
  {
    id: "daubert",
    title: "Expert testimony (Daubert)",
    rules: ["Daubert", "Rule 702"],
    facts:
      "In a toxic tort case, the plaintiff offers an expert who testifies that exposure to a chemical “more likely than not” caused the plaintiff’s illness, relying on a novel statistical model not widely peer-reviewed.",
    expected: "Daubert / Rule 702 factors; reliability, methodology, general acceptance.",
  },
  {
    id: "impeachment",
    title: "Impeachment / credibility (FRE 402, Hearsay)",
    rules: ["FRE 402", "Hearsay"],
    facts:
      "A key eyewitness testifies for the prosecution. The defense seeks to introduce evidence that the witness previously lied on a job application about academic credentials.",
    expected: "Impeachment by prior dishonest acts; limits on extrinsic evidence; discretion of the court.",
  },
  {
    id: "authentication-digital",
    title: "Authentication / digital evidence (FRE 401, Daubert)",
    rules: ["FRE 401", "Daubert"],
    facts:
      "The prosecution offers Instagram DMs allegedly sent by the defendant admitting involvement in a crime. The defendant argues the account was hacked and the messages are unauthenticated.",
    expected: "Authentication standards for digital evidence; circumstantial proof; threshold admissibility.",
  },
]

function promptToText(p: Prompt) {
  const lines: string[] = []
  lines.push(p.title)
  lines.push("")
  lines.push(`Rules: ${p.rules.join(", ")}`)
  lines.push("")
  lines.push(`Facts: ${p.facts}`)
  if (p.expected?.trim()) {
    lines.push("")
    lines.push(`What you should expect: ${p.expected}`)
  }
  return lines.join("\n")
}

export default function PromptsPage() {
  const [copiedId, setCopiedId] = React.useState<string | null>(null)

  async function onCopy(p: Prompt) {
    await navigator.clipboard.writeText(promptToText(p))
    setCopiedId(p.id)
    window.setTimeout(() => setCopiedId((cur) => (cur === p.id ? null : cur)), 1200)
  }

  return (
    <>
      <HeroHeader />
      <main className="min-h-[100svh] px-6 py-14 sm:py-20">
        <div className="relative mx-auto w-full max-w-5xl">
          {/* Subtle hero backdrop (static) */}
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-x-0 -top-10 -z-10 mx-auto h-72 max-w-5xl"
          >
            <div className="absolute inset-0 [background-image:linear-gradient(to_bottom,transparent_98%,theme(colors.border/60)_98%),linear-gradient(to_right,transparent_94%,_theme(colors.border/60)_94%)] [background-size:16px_34px] [mask:radial-gradient(black,transparent_70%)] opacity-60" />
            <div className="absolute left-1/2 top-10 h-40 w-2/3 -translate-x-1/2 rounded-full bg-primary/20 blur-3xl" />
          </div>

          <div className="flex flex-col items-center gap-6 sm:gap-8">
            <div className="text-center">
              <h1 className="mt-2 text-balance text-3xl font-semibold tracking-tight sm:text-4xl">
                Sample Prompts
              </h1>
              <p className="text-muted-foreground mt-3 max-w-2xl text-balance text-sm sm:text-base">
                Copy a prompt and paste it into Matlock to see what objection-ready authority should look like.
              </p>
            </div>
          </div>

          <div className="mt-12 grid gap-6">
            {PROMPTS.map((p) => (
              <Card key={p.id} className="p-6 sm:p-8">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                  <div className="min-w-0">
                    <h2 className="text-balance text-xl font-semibold">{p.title}</h2>
                    <div className="mt-3 flex flex-wrap gap-2">
                      {p.rules.map((r) => (
                        <span
                          key={r}
                          className="rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-medium text-primary"
                        >
                          {r}
                        </span>
                      ))}
                    </div>
                  </div>

                  <Button
                    type="button"
                    variant="outline"
                    className="shrink-0"
                    onClick={() => onCopy(p)}
                  >
                    {copiedId === p.id ? "Copied" : "Copy"}
                  </Button>
                </div>

                <div className="mt-5 space-y-3 text-muted-foreground">
                  <p className="leading-relaxed">
                    <span className="font-semibold text-foreground">Facts:</span> {p.facts}
                  </p>
                  {p.expected ? (
                    <p className="leading-relaxed">
                      <span className="font-semibold text-foreground">What you should expect:</span> {p.expected}
                    </p>
                  ) : null}
                </div>
              </Card>
            ))}
          </div>
        </div>
      </main>
    </>
  )
}

